# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'bms_condition.ui'
##
## Created by: Qt User Interface Compiler version 6.7.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGroupBox, QLabel, QLineEdit,
    QListView, QListWidget, QListWidgetItem, QMainWindow,
    QRadioButton, QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(862, 604)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 90, 41, 16))
        self.total_value = QLineEdit(self.centralwidget)
        self.total_value.setObjectName(u"total_value")
        self.total_value.setGeometry(QRect(80, 90, 41, 20))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 160, 41, 16))
        self.total_current = QLineEdit(self.centralwidget)
        self.total_current.setObjectName(u"total_current")
        self.total_current.setGeometry(QRect(80, 160, 41, 20))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 230, 54, 16))
        self.ave_tem = QLineEdit(self.centralwidget)
        self.ave_tem.setObjectName(u"ave_tem")
        self.ave_tem.setGeometry(QRect(80, 230, 41, 20))
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(150, 10, 431, 341))
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 30, 61, 16))
        self.bt_type = QLineEdit(self.groupBox)
        self.bt_type.setObjectName(u"bt_type")
        self.bt_type.setGeometry(QRect(100, 30, 81, 20))
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 80, 71, 16))
        self.bt_value = QLineEdit(self.groupBox)
        self.bt_value.setObjectName(u"bt_value")
        self.bt_value.setGeometry(QRect(100, 80, 81, 20))
        self.bt_value.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 130, 54, 16))
        self.bt_power = QLineEdit(self.groupBox)
        self.bt_power.setObjectName(u"bt_power")
        self.bt_power.setGeometry(QRect(100, 130, 81, 20))
        self.bt_power.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 170, 71, 16))
        self.charge_mos_on = QRadioButton(self.groupBox)
        self.charge_mos_on.setObjectName(u"charge_mos_on")
        self.charge_mos_on.setGeometry(QRect(100, 170, 51, 20))
        self.charge_mos_off = QRadioButton(self.groupBox)
        self.charge_mos_off.setObjectName(u"charge_mos_off")
        self.charge_mos_off.setGeometry(QRect(150, 170, 51, 20))
        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 210, 91, 16))
        self.charge_average_on = QRadioButton(self.groupBox)
        self.charge_average_on.setObjectName(u"charge_average_on")
        self.charge_average_on.setGeometry(QRect(100, 210, 41, 20))
        self.charge_average_off = QRadioButton(self.groupBox)
        self.charge_average_off.setObjectName(u"charge_average_off")
        self.charge_average_off.setGeometry(QRect(150, 210, 51, 20))
        self.label_9 = QLabel(self.groupBox)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 260, 54, 16))
        self.label_10 = QLabel(self.groupBox)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 310, 71, 16))
        self.bt_tem = QLineEdit(self.groupBox)
        self.bt_tem.setObjectName(u"bt_tem")
        self.bt_tem.setGeometry(QRect(100, 260, 81, 20))
        self.bt_tem.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.mos_tem = QLineEdit(self.groupBox)
        self.mos_tem.setObjectName(u"mos_tem")
        self.mos_tem.setGeometry(QRect(100, 310, 81, 20))
        self.mos_tem.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_11 = QLabel(self.groupBox)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(230, 30, 54, 16))
        self.bt_amount = QLineEdit(self.groupBox)
        self.bt_amount.setObjectName(u"bt_amount")
        self.bt_amount.setGeometry(QRect(320, 30, 81, 20))
        self.bt_amount.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_12 = QLabel(self.groupBox)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(230, 80, 41, 16))
        self.bt_current = QLineEdit(self.groupBox)
        self.bt_current.setObjectName(u"bt_current")
        self.bt_current.setGeometry(QRect(320, 80, 81, 20))
        self.bt_current.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_13 = QLabel(self.groupBox)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(230, 130, 54, 16))
        self.bt_cd = QLineEdit(self.groupBox)
        self.bt_cd.setObjectName(u"bt_cd")
        self.bt_cd.setGeometry(QRect(320, 130, 81, 20))
        self.label_14 = QLabel(self.groupBox)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(230, 170, 71, 16))
        self.discharge_mos_on = QRadioButton(self.groupBox)
        self.discharge_mos_on.setObjectName(u"discharge_mos_on")
        self.discharge_mos_on.setGeometry(QRect(320, 170, 41, 20))
        self.discharge_mos_off = QRadioButton(self.groupBox)
        self.discharge_mos_off.setObjectName(u"discharge_mos_off")
        self.discharge_mos_off.setGeometry(QRect(370, 170, 51, 20))
        self.label_15 = QLabel(self.groupBox)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(230, 210, 81, 16))
        self.tem_pro_on = QRadioButton(self.groupBox)
        self.tem_pro_on.setObjectName(u"tem_pro_on")
        self.tem_pro_on.setGeometry(QRect(320, 210, 41, 20))
        self.tem_pro_off = QRadioButton(self.groupBox)
        self.tem_pro_off.setObjectName(u"tem_pro_off")
        self.tem_pro_off.setGeometry(QRect(370, 210, 51, 20))
        self.label_16 = QLabel(self.groupBox)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(230, 260, 71, 16))
        self.now_tem = QLineEdit(self.groupBox)
        self.now_tem.setObjectName(u"now_tem")
        self.now_tem.setGeometry(QRect(320, 260, 81, 20))
        self.now_tem.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_17 = QLabel(self.groupBox)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(230, 310, 81, 16))
        self.inside_tem = QLineEdit(self.groupBox)
        self.inside_tem.setObjectName(u"inside_tem")
        self.inside_tem.setGeometry(QRect(320, 310, 81, 20))
        self.inside_tem.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(20, 370, 821, 191))
        self.bt_1 = QListView(self.groupBox_3)
        self.bt_1.setObjectName(u"bt_1")
        self.bt_1.setGeometry(QRect(20, 60, 81, 101))
        self.bt_1.setStyleSheet(u"border: 1px solid black;")
        self.bt_2 = QListView(self.groupBox_3)
        self.bt_2.setObjectName(u"bt_2")
        self.bt_2.setGeometry(QRect(120, 60, 81, 101))
        self.bt_2.setStyleSheet(u"border: 1px solid black;")
        self.bt_3 = QListWidget(self.groupBox_3)
        self.bt_3.setObjectName(u"bt_3")
        self.bt_3.setGeometry(QRect(220, 60, 81, 101))
        self.bt_3.setStyleSheet(u"border: 1px solid black;")
        self.bt_4 = QListView(self.groupBox_3)
        self.bt_4.setObjectName(u"bt_4")
        self.bt_4.setGeometry(QRect(320, 60, 81, 101))
        self.bt_4.setStyleSheet(u"border: 1px solid black;")
        self.bt_5 = QListView(self.groupBox_3)
        self.bt_5.setObjectName(u"bt_5")
        self.bt_5.setGeometry(QRect(420, 60, 81, 101))
        self.bt_5.setStyleSheet(u"border: 1px solid black;")
        self.bt_6 = QListView(self.groupBox_3)
        self.bt_6.setObjectName(u"bt_6")
        self.bt_6.setGeometry(QRect(520, 60, 81, 101))
        self.bt_6.setStyleSheet(u"border: 1px solid black;")
        self.bt_7 = QListView(self.groupBox_3)
        self.bt_7.setObjectName(u"bt_7")
        self.bt_7.setGeometry(QRect(620, 60, 81, 101))
        self.bt_7.setStyleSheet(u"border: 1px solid black;")
        self.bt_8 = QListView(self.groupBox_3)
        self.bt_8.setObjectName(u"bt_8")
        self.bt_8.setGeometry(QRect(720, 60, 81, 101))
        self.bt_8.setStyleSheet(u"border: 1px solid black;")
        self.label_26 = QLabel(self.groupBox_3)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(40, 30, 31, 16))
        self.label_26.setAlignment(Qt.AlignmentFlag.AlignJustify|Qt.AlignmentFlag.AlignVCenter)
        self.label_27 = QLabel(self.groupBox_3)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(140, 30, 31, 16))
        self.label_27.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_28 = QLabel(self.groupBox_3)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(240, 30, 31, 16))
        self.label_29 = QLabel(self.groupBox_3)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(340, 30, 31, 16))
        self.label_30 = QLabel(self.groupBox_3)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(440, 30, 31, 16))
        self.label_31 = QLabel(self.groupBox_3)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(540, 30, 31, 16))
        self.label_32 = QLabel(self.groupBox_3)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(640, 30, 31, 16))
        self.label_33 = QLabel(self.groupBox_3)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(740, 30, 31, 16))
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(600, 10, 241, 341))
        self.label_18 = QLabel(self.groupBox_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(20, 30, 71, 16))
        self.bt_ht = QLineEdit(self.groupBox_2)
        self.bt_ht.setObjectName(u"bt_ht")
        self.bt_ht.setGeometry(QRect(130, 30, 91, 20))
        self.bt_ht.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_19 = QLabel(self.groupBox_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(20, 70, 111, 16))
        self.bt_soc = QLineEdit(self.groupBox_2)
        self.bt_soc.setObjectName(u"bt_soc")
        self.bt_soc.setGeometry(QRect(130, 70, 91, 20))
        self.bt_soc.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_20 = QLabel(self.groupBox_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(20, 110, 81, 16))
        self.bt_cycle = QLineEdit(self.groupBox_2)
        self.bt_cycle.setObjectName(u"bt_cycle")
        self.bt_cycle.setGeometry(QRect(130, 110, 91, 20))
        self.bt_cycle.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_21 = QLabel(self.groupBox_2)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(20, 150, 81, 16))
        self.max_value = QLineEdit(self.groupBox_2)
        self.max_value.setObjectName(u"max_value")
        self.max_value.setGeometry(QRect(130, 150, 91, 20))
        self.max_value.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_22 = QLabel(self.groupBox_2)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(20, 190, 81, 16))
        self.min_value = QLineEdit(self.groupBox_2)
        self.min_value.setObjectName(u"min_value")
        self.min_value.setGeometry(QRect(130, 190, 91, 20))
        self.min_value.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_23 = QLabel(self.groupBox_2)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(20, 230, 81, 16))
        self.ave_value = QLineEdit(self.groupBox_2)
        self.ave_value.setObjectName(u"ave_value")
        self.ave_value.setGeometry(QRect(130, 230, 91, 20))
        self.ave_value.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_24 = QLabel(self.groupBox_2)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(20, 270, 81, 16))
        self.df_max = QLineEdit(self.groupBox_2)
        self.df_max.setObjectName(u"df_max")
        self.df_max.setGeometry(QRect(132, 270, 91, 20))
        self.df_max.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.tem_probe = QLineEdit(self.groupBox_2)
        self.tem_probe.setObjectName(u"tem_probe")
        self.tem_probe.setGeometry(QRect(132, 310, 91, 20))
        self.tem_probe.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_25 = QLabel(self.groupBox_2)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(20, 310, 81, 16))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u603b\u7535\u538b\uff1a", None))
        self.total_value.setText(QCoreApplication.translate("MainWindow", u"0V", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u603b\u7535\u6d41\uff1a", None))
        self.total_current.setText(QCoreApplication.translate("MainWindow", u"0A", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u5e73\u5747\u6e29\u5ea6\uff1a", None))
        self.ave_tem.setText(QCoreApplication.translate("MainWindow", u"0\u00b0C", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"\u7efc\u5408\u4fe1\u606f\u680f", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u7535\u6c60\u7c7b\u578b:", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u7535\u6c60\u603b\u7535\u538b\uff1a", None))
        self.bt_value.setText(QCoreApplication.translate("MainWindow", u"V", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u7535\u6c60\u529f\u7387\uff1a", None))
        self.bt_power.setText(QCoreApplication.translate("MainWindow", u"W", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u5145\u7535MOS\u7ba1\uff1a", None))
        self.charge_mos_on.setText(QCoreApplication.translate("MainWindow", u"ON", None))
        self.charge_mos_off.setText(QCoreApplication.translate("MainWindow", u"OFF", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u5145\u7535\u5747\u8861\u5f00\u5173\u7ba1\uff1a", None))
        self.charge_average_on.setText(QCoreApplication.translate("MainWindow", u"ON", None))
        self.charge_average_off.setText(QCoreApplication.translate("MainWindow", u"OFF", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\u7535\u6c60\u6e29\u5ea6\uff1a", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"MOS\u7ba1\u6e29\u5ea6\uff1a", None))
        self.bt_tem.setText(QCoreApplication.translate("MainWindow", u"\u00b0C", None))
        self.mos_tem.setText(QCoreApplication.translate("MainWindow", u"\u00b0C", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"\u7535\u6c60\u4e32\u6570\uff1a", None))
        self.bt_amount.setText(QCoreApplication.translate("MainWindow", u"\u4e32", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"\u603b\u7535\u6d41\uff1a", None))
        self.bt_current.setText(QCoreApplication.translate("MainWindow", u"A", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"\u7535\u6c60\u72b6\u6001\uff1a", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"\u653e\u7535MOS\u7ba1\uff1a", None))
        self.discharge_mos_on.setText(QCoreApplication.translate("MainWindow", u"ON", None))
        self.discharge_mos_off.setText(QCoreApplication.translate("MainWindow", u"OFF", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"\u6e29\u5ea6\u4fdd\u62a4\u5f00\u5173\uff1a", None))
        self.tem_pro_on.setText(QCoreApplication.translate("MainWindow", u"ON", None))
        self.tem_pro_off.setText(QCoreApplication.translate("MainWindow", u"OFF", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"\u5f53\u524d\u6e7f\u5ea6\u503c\uff1a", None))
        self.now_tem.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"\u7535\u6c60\u7bb1\u5185\u6e29\u5ea6\uff1a", None))
        self.inside_tem.setText(QCoreApplication.translate("MainWindow", u"\u00b0C", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"\u5355\u8282\u7535\u6c60\u7535\u538b", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"\u7535\u6c601", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"\u7535\u6c602", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"\u7535\u6c603", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"\u7535\u6c604", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"\u7535\u6c605", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"\u7535\u6c606", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"\u7535\u6c607", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"\u7535\u6c608", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"\u5176\u4ed6\u4fe1\u606f\u680f", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"\u7535\u6c60\u5065\u5eb7\u5ea6\uff1a", None))
        self.bt_ht.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"\u7535\u6c60\u5269\u4f59\u7535\u91cfSOC\uff1a", None))
        self.bt_soc.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"\u7535\u6c60\u5faa\u73af\u6b21\u6570\uff1a", None))
        self.bt_cycle.setText(QCoreApplication.translate("MainWindow", u"\u6b21", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"\u7535\u82af\u6700\u9ad8\u7535\u538b\uff1a", None))
        self.max_value.setText(QCoreApplication.translate("MainWindow", u"mV", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"\u7535\u82af\u6700\u4f4e\u7535\u538b\uff1a", None))
        self.min_value.setText(QCoreApplication.translate("MainWindow", u"mV", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"\u7535\u82af\u5e73\u5747\u7535\u538b\uff1a", None))
        self.ave_value.setText(QCoreApplication.translate("MainWindow", u"mV", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"\u6700\u5927\u7535\u82af\u538b\u5dee\uff1a", None))
        self.df_max.setText(QCoreApplication.translate("MainWindow", u"mV", None))
        self.tem_probe.setText(QCoreApplication.translate("MainWindow", u"\u4e2a", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"\u7535\u6c60\u6e29\u5ea6\u63a2\u5934\uff1a", None))
    # retranslateUi

